site_name: Fourier GRX Client

repo_url: https://github.com/FFTAI/fourier-grx-client
edit_uri: edit/main/docs

theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Open Sans
    code: Fira Code
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky

plugins:
  - search
  - markdown-exec
  - "mkdocs-version-annotations":
      version_added_admonition: "tip"
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            docstring_style: google
  # - redirects:
  #     redirect_maps:

nav:
  - Usage:
      - Introduction: index.md
      - Calibration: tutorials/calibration.md

  - Reference:
      - reference/cli.md
      - reference/api.md
  - Changelog: dev/changelog.md

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets:
      restrict_base_path: false
  - admonition
  - tables
  - toc:
      permalink: "#"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: Copyright &copy; 2024 <a href="https://fourierintelligence.com/">Fourier</a>

extra:
  version:
    provider: mike

watch:
  - src
